CI: update
Signed-off-by: Marty Jones <mj8263788@gmail.com>

diff --git a/.github/workflows/rockchip-aarch64.yml b/.github/workflows/rockchip-aarch64.yml
--- a/.github/workflows/rockchip-aarch64.yml
+++ b/.github/workflows/rockchip-aarch64.yml
@@ -4,18 +4,29 @@ on:
 jobs:
     build:
         name: Build rockchip aarch64
-        runs-on: ubuntu-24.04-arm
+        runs-on: ubuntu-26.04-arm
         steps:
+            - name: Maximize build space
+              uses: easimon/maximize-build-space@master
+              with:
+                   root-reserve-mb: 512
+                   swap-size-mb: 1024
+                   remove-dotnet: 'true'
+                   overprovision-lvm: 'true'
+                   remove-android: 'true'
+                   remove-haskell: 'true'
+                   remove-codeql: 'true'
+                   remove-docker-images: 'true'
             - name: Setup Ubuntu
               run: |
                 sudo apt update
-                sudo apt install -y subversion build-essential gettext 2to3 python3-pyelftools python3-distutils-extra
+                sudo apt install -y subversion patch build-essential gettext python3-pyelftools python3-distutils-extra
             - name: Setup Go
-              uses: actions/setup-go@v5
+              uses: actions/setup-go@main
               with:
-                go-version: '1.24.4'
+                go-version: '1.26.3'
             - name: checkout
-              uses: actions/checkout@v4
+              uses: actions/checkout@main
             - name: Build
               run: |
                 git clone https://github.com/openwrt/openwrt.git
@@ -25,18 +36,28 @@ jobs:
                 git switch linux-6.6
                 git format-patch main...linux-6.6 --stdout > 001.patch
                 git checkout main
-                git apply 001.patch
+                patch -p 1 -i 001.patch
                 ./scripts/feeds update -a
                 ./scripts/feeds install -a
                 cd feeds/luci
+                wget https://github.com/mj22226/luci/commit/ecafd7945729f8bf01fd9cd2f13e57af79b51027.patch
+                git apply ecafd7945729f8bf01fd9cd2f13e57af79b51027.patch
                 wget https://gist.githubusercontent.com/mj22226/363cefecd314e45b49d8eafff8473fcf/raw/f327d1fcae5513be3abbeea1c6696c1da845a635/01-diskman.patch
-
+                wget https://github.com/mj22226/luci/commit/165cb1fd697c90a0d92b817624ae2378c7e77a1e.patch
                 git apply 01-diskman.patch
-
+                git apply 165cb1fd697c90a0d92b817624ae2378c7e77a1e.patch
+                wget https://github.com/mj22226/luci/commit/239fd8e34a7e3d85d104be72b385ce46ccb9dfb4.patch
+                rm -rf applications/luci-app-dockerman
+                git apply 239fd8e34a7e3d85d104be72b385ce46ccb9dfb4.patch
                 cd -
                 cd  feeds/packages
+                rm -rf net/openvpn
+                wget https://github.com/mj22226/packages/commit/27453c364f0d9513bf10f30d2e2f863b0a4b0267.patch
+                git apply 27453c364f0d9513bf10f30d2e2f863b0a4b0267.patch
+                wget https://gist.githubusercontent.com/mj22226/351f11e66f08f06e37a985719a31ddb4/raw/2cf67633587d351b66fdf1bd902df6494cd42e68/01-cpu.patch
                 wget https://gist.githubusercontent.com/mj22226/b66f5c1bd5fc7e1cb3cf2c690b5dbd5a/raw/b955e726cbb0948d932c8d6143229ad604320149/20-lxc.patch
                 git apply 20-lxc.patch
+                git apply 01-cpu.patch
                 cd -
                 sed -i "71s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                 sed -i "84s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
@@ -44,14 +65,21 @@ jobs:
                 sed -i "212s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                 sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                 sed -i "4s/login/login -f root/" feeds/packages/utils/ttyd/files/ttyd.config
+                sed -i '12d' feeds/luci/applications/luci-app-attendedsysupgrade/Makefile
+                rm -f target/linux/generic/hack-6.12/930-Revert-Revert-Revert-driver-core-Set-fw_devlink-on-b.patch || true
+                rm -f target/linux/generic/hack-6.18/930-Revert-Revert-Revert-driver-core-Set-fw_devlink-on-b.patch
                 ./scripts/feeds update -a
                 ./scripts/feeds install -a -f
-                wget https://github.com/mj22226/openwrt-arm64/releases/download/rockchip-20.1.8/llvm-bpf-20.1.8.Linux-aarch64.tar.zst
-                tar -xvf llvm-bpf-20.1.8.Linux-aarch64.tar.zst
+                wget https://github.com/mj22226/openwrt-arm64/releases/download/rockchip-22.1.3/llvm-bpf-22.1.3.Linux-aarch64.tar.zst
+                tar -xvf llvm-bpf-22.1.3.Linux-aarch64.tar.zst
                 cp .github/workflows/rk-config .config
-                echo "# CONFIG_ARM64_CONTPTE is not set" >> target/linux/generic/config-6.12
-                echo "# CONFIG_DRM_WERROR is not set" >> target/linux/generic/config-6.12
-                echo 'CONFIG_GOLANG_EXTERNAL_BOOTSTRAP_ROOT="/opt/hostedtoolcache/go/1.24.4/arm64/bin"' >> .config
+                echo "# CONFIG_ARM64_CONTPTE is not set" >> target/linux/generic/config-6.12 || true
+                echo "# CONFIG_DRM_WERROR is not set" >> target/linux/generic/config-6.12 || true
+                echo 'CONFIG_GOLANG_EXTERNAL_BOOTSTRAP_ROOT="/opt/hostedtoolcache/go/1.26.3/arm64/bin"' >> .config
+                echo "# CONFIG_DRM_WERROR is not set" >> target/linux/generic/config-6.18
+                echo "# CONFIG_ARM64_BRBE is not set" >> target/linux/generic/config-6.18
+                echo "# CONFIG_CRASH_DM_CRYPT is not set" >> target/linux/generic/config-6.18
+                echo "# CONFIG_DRM_WERROR is not set" >> target/linux/generic/config-6.18 || true
                 make defconfig
                 wget https://gist.githubusercontent.com/mj22226/9a69bb754a83e8a5cf03fcc60d62d473/raw/cc6f36831d6098de4a7fccf04a312d36a0dbc999/01-key.patch
                 git apply 01-key.patch
@@ -72,7 +100,7 @@ jobs:
               env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             - name: Create release
-              uses: ncipollo/release-action@v1.14.0
+              uses: ncipollo/release-action@main
               with:
                 allowUpdates: true
                 name: Rockchip v6.12 Firmware Images ${{ env.D }}
